#!/usr/bin/env bash
set -ex


# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.


# Uncomment the following line to run all simulations and plot the results. 

bash runEverything.sh 

# This one will skip the simulations and just use the uploaded data to plot the results 

#bash plotEverything.sh
